logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0 
  zipkin:
    tracing:
      endpoint: ${OTEL_COLLECTOR_URI:localhost:4317}
