apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dlink-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.3.0/22
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dlink-ip-pool-advertise
  namespace: metallb-system
spec:
  ipAddressPools:
  - dlink-ip-pool

