# 1) 빌드 단계
FROM node:20-alpine AS builder

# 작업 디렉터리 생성
WORKDIR /app

ENV NODE_OPTIONS=--openssl-legacy-provider
COPY ./package.json ./
# Git 설치 (GitHub 패키지 문제 방지)
RUN apk add --no-cache git

# 패키지 매니저 캐시 클리어 및 의존성 설치
RUN npm cache clean --force
RUN npm install --legacy-peer-deps

# 소스 전체 복사
COPY . .

# Standalone 모드로 Next.js 프로덕션 빌드
RUN npm run build

# 2) 실행 단계
FROM node:20-alpine AS runner

# 실행 환경 설정
WORKDIR /app
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
