apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: dlk-monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        zipkin:
          endpoint: 0.0.0.0:9411

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo

