apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: dlk-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args: ["-config.file=/conf/tempo.yaml"]
          volumeMounts:
            - name: tempo-config
              mountPath: /conf
              readOnly: true
            - name: tempo-data
              mountPath: /var/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-data

