apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: dlk-monitoring
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      zipkin:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
      zipkin:
        endpoint: http://tempo:9412/api/v2/spans
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp, zipkin]
          processors: [batch]
          exporters: [debug, otlp, zipkin]
