apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-be-pairing-pairing-deploy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: spring-container
          image: 192.168.3.81/dlink/pairing-service:v2.0.5

