apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-be-alcohol-review-deploy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: spring-container
          image: 192.168.3.81/dlink/review-service:v2.0.5

