apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dlk-kafka-wineconsumer-statefulset
  namespace: dlk-kafka
spec:
  serviceName: "dlk-kafka-wineconsumer"
  replicas: 1
  selector:
    matchLabels:
      app: wine-consumer
  template:
    metadata:
      labels:
        app: wine-consumer
    spec:
      containers:
      - name: wine-consumer
        image: 192.168.3.81/dlink/wineconsumer:v2.0.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: dlk-kafka-wineconsumer-config
        - secretRef:
            name: dlk-kafka-accesskey-secret
        volumeMounts:
        - name: wineconsumer-storage
          mountPath: /var/lib/kafka
      volumes:
      - name: wineconsumer-storage
        emptyDir: {}
