apiVersion: v1
kind: Service
metadata:
  name: dlk-kafka-wineconsumer-service
  namespace: dlk-kafka
spec:
  clusterIP: None
  selector:
    app: wine-consumer
  ports:
    - name: kafka-wineconsumer
      port: 9092
      targetPort: 9092

