apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: dlk-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: openebs-hostpath
