apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: dlk-monitoring
spec:
  selector:
    matchLabels:
      app: otel-collector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.94.0
          args: ["--config=/conf/collector.yaml"]
          volumeMounts:
            - name: otel-config
              mountPath: /conf
              readOnly: true
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config

