apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dlk-kafka-highballconsumer-statefulset
  namespace: dlk-kafka
spec:
  serviceName: "dlk-kafka-highballconsumer"
  replicas: 1
  selector:
    matchLabels:
      app: highball-consumer
  template:
    metadata:
      labels:
        app: highball-consumer
    spec:
      containers:
      - name: highball-consumer
        image: 192.168.3.81/dlink/highballconsumer:v2.0.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: dlk-kafka-highballconsumer-config
        - secretRef:
            name: dlk-kafka-accesskey-secret
        volumeMounts:
        - name: highballconsumer-storage
          mountPath: /var/lib/kafka
      volumes:
      - name: highballconsumer-storage
        emptyDir: {}
