apiVersion: v1
kind: Service
metadata:
  name: dlk-kafka-ui-service
  namespace: dlk-monitoring
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: NodePort

