apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: dlk-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master

---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: dlk-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: slave

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: dlk-redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 31630
    name: write
  - port: 6380
    targetPort: 6380
    nodePort: 30719
    name: read
  selector:
    app: haproxy

