apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
  namespace: dlk-redis
spec:
  serviceName: redis-slave
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis
        image: redis:6.2
        command: ["redis-server", "--replicaof", "redis-master", "6379"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc

