apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: dlk-monitoring
data:
  fluent.conf: |
    # 1) Fluentd 자체 로그는 버림
    <match fluent.**>
      @type null
    </match>

    # 2) CRI 표준 포맷 로그 수집
    <source>
      @type tail
      path /var/log/containers/*
      pos_file /var/log/containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type cri
      </parse>
    </source>

    # 3) K8s 메타데이터 추가
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    # 4) 로그 시간/Pod 이름을 레코드에 저장
    #   - log_time : CRI 파서가 추출한 `timestamp` 필드가 있으면 사용, 없으면 현재 이벤트 시각 사용
    #   - prefix_field_name : 인덱스 접두어로 쓸 Pod 이름
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        # CRI 로그에 "timestamp"가 있으면 그 값을 쓰고,
        # 없으면 fallback으로 Fluentd 이벤트 시간(ISO8601) 사용
        log_time ${record["timestamp"] || time.strftime('%Y-%m-%dT%H:%M:%S.%N%z')}

        # Pod 이름을 인덱스 접두어 키에 저장
        prefix_field_name ${record["kubernetes"]["pod_name"]}
      </record>
      remove_keys timestamp
    </filter>

    # 5) 특정 네임스페이스 로그 무시
    <match kubernetes.var.log.**dlk-cicd**>
      @type null
    </match>
    <match kubernetes.var.log.**dlk-monitoring**>
      @type null
    </match>
    <match kubernetes.var.log.**dlk-redis**>
      @type null
    </match>
    <match kubernetes.var.log.**openebs**>
      @type null
    </match>
    <match kubernetes.var.log.**kube-system**>
      @type null
    </match>
    <match kubernetes.var.log.**metallb-system**>
      @type null
    </match>

    # 6) Elasticsearch로 전송
    #   - logstash_format=true : 인덱스 이름에 날짜 자동 추가
    #   - logstash_prefix_key : Pod 이름을 인덱스 접두어로 사용
    <match kubernetes.**>
      @type elasticsearch
      logstash_format true
      logstash_prefix_key prefix_field_name   # Pod 이름이 인덱스 prefix
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
      include_tag_key true
      reload_connections true

      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever true
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 32
        overflow_action block
      </buffer>
    </match>

