apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-monitoring-role
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - services
  - events
  - configmaps
  - endpoints
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - replicationcontrollers
  - secrets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-monitoring-role-binding
subjects:
- kind: ServiceAccount
  name: fluentd-sa
  namespace: dlk-monitoring
roleRef:
  kind: ClusterRole
  name: fluentd-monitoring-role
  apiGroup: rbac.authorization.k8s.io

