services:

  kafka:
    build:
      context: ./kafka/broker
      dockerfile: Dockerfile
    container_name: kafka-broker-2
    environment:
      - BROKER_ID=2
      - ZOOKEEPER_CONNECT=192.168.3.81:2181
      - LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ADVERTISED_LISTENERS=PLAINTEXT://192.168.3.82:9092
      - LOG_DIRS=/var/lib/kafka/logs-2
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - ./kafka/logs-2:/var/lib/kafka/logs-2
    ports:
      - "9092:9092"
    networks:
      - kafka_net
    restart: unless-stopped

  yangjuproducer:
    build:
      context: ./kafka/producer/yangju
      dockerfile: Dockerfile
    container_name: yangjuproducer
    environment:
      - PYTHONUNBUFFERED=1
      - KAFKA_BROKERS=192.168.3.81:9092,192.168.3.82:9092,192.168.3.83:9092
    volumes:
      - ./kafka/producer/yangju:/app
    working_dir: /app
    command: ["python", "yangjuProducer.py"]
    networks:
      - kafka_net
    depends_on:
      - kafka
    restart: unless-stopped

  highballproducer: 
    build: 
      context: ./kafka/producer/highball
      dockerfile: Dockerfile
    container_name: highballproducer
    environment: 
      - PYTHONUNBUFFERED=1
      - KAFKA_BROKERS=192.168.3.81:9092,192.168.3.82:9092,192.168.3.83:9092
    volumes: 
      - ./kafka/producer/highball:/app
    working_dir: /app
    command: ["python", "highballProducer.py"]
    networks: 
      - kafka_net
    depends_on: 
      - kafka
    restart: unless-stopped

networks:
  kafka_net:
    driver: bridge

