apiVersion: v1
kind: ConfigMap
metadata:
  name: dlk-kafka-yangjuproducer-config
  namespace: dlk-kafka
data:
  MONGO_URI: "mongodb://admin:admin@192.168.3.81:27017"
  DB_NAME: "dlink_db"
  COLLECTION_NAME: "brandy,gin,rum,liqueur,tequila,vodka,whiskey"
  KAFKA_BROKERS: "dlk-kafka-broker1-service.dlk-kafka.svc.cluster.local:9092,dlk-kafka-broker2-service.dlk-kafka.svc.cluster.local:9093,dlk-kafka-broker3-service.dlk-kafka.svc.cluster.local:9094"
  KAFKA_TOPIC: "brandyTopic,ginTopic,rumTopic,liqueurTopic,tequilaTopic,vodkaTopic,whiskeyTopic"

