apiVersion: v1
kind: ConfigMap
metadata:
  name: dlk-kafka-highballproducer-config
  namespace: dlk-kafka
data:
  MONGO_URI: "mongodb://192.168.3.200:27017"
  DB_NAME: "dlink_db"
  COLLECTION_NAME: "highball"
  KAFKA_BROKERS: "dlk-kafka-broker1-service.dlk-kafka.svc.cluster.local:9092,dlk-kafka-broker2-service.dlk-kafka.svc.cluster.local:9093,dlk-kafka-broker3-service.dlk-kafka.svc.cluster.local:9094"
  KAFKA_TOPIC: "highballTopic"

