apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dlk-kafka-broker1
  namespace: dlk-kafka
spec:
  serviceName: dlk-kafka-broker1-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker1
  template:
    metadata:
      labels:
        app: kafka-broker1
    spec:
      containers:
        - name: kafka-broker
          image: 192.168.3.81/dlink/kafka:v2.0.0
          ports:
            - containerPort: 9092
              name: kafka
          envFrom:
            - configMapRef:
                name: dlk-kafka-broker1-config
          volumeMounts:
            - name: kafka-logs
              mountPath: /var/lib/kafka/logs-1
      volumes:
        - name: kafka-logs
          emptyDir: {}   
 
