apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dlk-kafka-broker2
  namespace: dlk-kafka
spec:
  serviceName: dlk-kafka-broker2-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker2
  template:
    metadata:
      labels:
        app: kafka-broker2
    spec:
      containers:
        - name: kafka-broker
          image: 192.168.3.81/dlink/kafka:v2.0.0
          ports:
            - containerPort: 9093
              name: kafka
          envFrom:
            - configMapRef:
                name: dlk-kafka-broker2-config
          volumeMounts:
            - name: kafka-logs
              mountPath: /var/lib/kafka/logs-2
      volumes:
        - name: kafka-logs
          emptyDir: {}

