kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-readonly-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-readonly-clusterrolebinding
subjects:
- kind: User
  name: ops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ops-readonly-clusterrole
  apiGroup: rbac.authorization.k8s.io


