kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sec-admin-clusterrole
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sec-admin-clusterrolebinding
subjects:
- kind: User
  name: sec
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sec-admin-clusterrole
  apiGroup: rbac.authorization.k8s.io


