
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: review-service
  name: dlk-be-alcohol-review-deploy
  namespace: dlk-be-alcohol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      imagePullSecrets:
        - name: dlk-be-alcohol-harbor-secrets
      containers:
        - envFrom:
            - secretRef:
                name: dlk-be-alcohol-secrets
            - configMapRef:
                name: dlk-be-alcohol-config
          image: 192.168.3.81/dlink/review-service:v2.0.0
          name: spring-container
          resources:
            requests:
              cpu: "50m"
              memory: "320Mi"
            limits:
              cpu: "1100m"
              memory: "512Mi"
