apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextjs
  name: dlk-fe-next-deploy
  namespace: dlk-fe-next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      imagePullSecrets:
        - name: dlk-fe-next-harbor-secrets
      containers:
        - name: nextjs-container
          image: 192.168.3.81/dlink/next-app:v2.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: dlk-fe-next-secrets
            - configMapRef:
                name: dlk-fe-next-config
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "700m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
      restartPolicy: Always

