apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-kafka-highballproducer-deploy
  namespace: dlk-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highballproducer
  template:
    metadata:
      labels:
        app: highballproducer
    spec:
      containers:
      - name: highballproducer
        image: 192.168.3.81/dlink/highballproducer:v2.0.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: dlk-kafka-highballproducer-config

