apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlk-cicd-sonarqube-deploy
  namespace: dlk-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube-container
          image: sonarqube:latest
          ports:
            - containerPort: 9000
