---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-svc
  namespace: dlk-cicd
spec:
  type: ClusterIP
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
