---
apiVersion: v1
kind: Service
metadata:
  name: dlk-cicd-trivy-svc
  namespace: dlk-cicd
spec:
  type: LoadBalancer
  selector:
    app: trivy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31112
