apiVersion: v1
kind: Service
metadata:
  name: dlk-gateway-svc
  namespace: dlk-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 8080
      nodePort: 30001
  type: NodePort
