apiVersion: v1
kind: Service
metadata:
  name: dlk-be-auth-svc
  namespace: dlk-be-auth
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: ClusterIP

