apiVersion: v1
kind: Service
metadata:
  name: dlk-be-review-svc
  namespace: dlk-be-alcohol
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP

