apiVersion: v1
kind: Service
metadata:
  name: dlk-be-alcohol-svc
  namespace: dlk-be-alcohol
spec:
  type: ClusterIP
  selector:
    app: alcohol-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
