apiVersion: v1
kind: Service
metadata:
  name: dlk-be-pairing-svc
  namespace: dlk-be-pairing
spec:
  selector:
    app: pairing-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
  type: ClusterIP

