apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextjs
  name: dlk-fe-next-svc
  namespace: dlk-fe-next
spec:
  type: NodePort
  ports:
    - name: "front"
      port: 2100
      targetPort: 3000
      nodePort: 32500
  selector:
    app: nextjs
