apiVersion: v1
kind: Service
metadata:
  name: dlk-be-highball-svc
  namespace: dlk-be-alcohol
spec:
  selector:
    app: highball-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: ClusterIP

